-- ============================================================
-- CardScout Unified App — Supabase Schema
-- Run this on a fresh Supabase project.
-- ============================================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- ============================================================
-- CARDS — global catalog, seeded from CSV
-- ============================================================
create table if not exists cards (
  id                      uuid primary key default uuid_generate_v4(),
  name                    text not null,
  issuer                  text not null,
  card_type               text not null default 'personal', -- personal | business | secured | student
  annual_fee              numeric not null default 0,
  reward_model            text,   -- cashback | travel | airline | hotel
  rewards_type            text,   -- "Ultimate Rewards (UR)" | "Cash" | etc.
  card_family             text,
  signup_bonus            text,
  signup_bonus_type       text,   -- points | dollars | miles
  estimated_bonus_value_usd text,
  minimum_spend_amount    text,
  spend_time_frame        text,
  cashback_rate_display   text,
  cashback_rate_effective text,
  gas_rate                text,
  grocery_rate            text,
  restaurant_rate         text,
  travel_airline_rate     text,
  travel_hotel_rate       text,
  travel_portal_rate      text,
  other_rate              text,
  lounge                  text,
  ge_tsa_precheck         text,
  transfer_partners       text,
  foreign_tx_fee          text,
  ftf                     text,
  intro_apr_purchase      text,
  best_for                text,
  pros                    text,
  cons                    text,
  bank_rules              text,
  application_link        text,   -- raw issuer URL, never transformed
  special_feature_1       text,
  special_feature_2       text,
  credit_score_quantity   text,
  credit_score_quality    text,
  gradient_key            text default 'default',
  image_path              text,
  is_active               boolean not null default true,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

create unique index if not exists cards_name_issuer_idx on cards (name, issuer);
create index if not exists cards_issuer_idx on cards (issuer);
create index if not exists cards_card_type_idx on cards (card_type);
create index if not exists cards_reward_model_idx on cards (reward_model);

-- ============================================================
-- BENEFITS — per-card benefit definitions
-- ============================================================
create table if not exists benefits (
  id                      uuid primary key default uuid_generate_v4(),
  card_id                 uuid not null references cards (id) on delete cascade,
  title                   text not null,
  description             text,
  value                   numeric,
  frequency               text not null, -- monthly | quarterly | semi-annual | annual | multi-year
  reset_logic             text,          -- calendar_month | calendar_year | account_anniversary
  reset_month             int,
  period_years            int default 1,
  reminder_default_days   int not null default 7,
  category                text,          -- travel | dining | entertainment | fitness | hotel | shopping
  is_active               boolean not null default true,
  sort_order              int not null default 0,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

create index if not exists benefits_card_id_idx on benefits (card_id);

-- ============================================================
-- USER_CARDS — cards saved by each user
-- ============================================================
create table if not exists user_cards (
  id               uuid primary key default uuid_generate_v4(),
  user_id          uuid not null references auth.users (id) on delete cascade,
  card_id          uuid not null references cards (id) on delete cascade,
  last_four        text,
  application_date date,
  nickname         text,
  created_at       timestamptz not null default now()
);

create unique index if not exists user_cards_user_card_idx on user_cards (user_id, card_id);
create index if not exists user_cards_user_id_idx on user_cards (user_id);

-- ============================================================
-- REMINDERS — generated by reminder engine per user_card
-- ============================================================
create table if not exists reminders (
  id                      uuid primary key default uuid_generate_v4(),
  user_id                 uuid not null references auth.users (id) on delete cascade,
  user_card_id            uuid not null references user_cards (id) on delete cascade,
  benefit_id              uuid not null references benefits (id) on delete cascade,
  period_label            text not null,  -- "Jan 2026", "Q1 2026", "2026"
  period_start            date not null,
  period_end              date not null,
  remind_at               date not null,
  status                  text not null default 'pending', -- pending | used | snoozed | expired
  snoozed_until           date,
  amount_used             numeric default 0,
  notifications_enabled   boolean not null default true,
  remind_via_email        boolean not null default true,
  remind_via_push         boolean not null default true,
  remind_via_ics          boolean not null default false,
  created_at              timestamptz not null default now()
);

create index if not exists reminders_user_id_idx on reminders (user_id);
create index if not exists reminders_user_card_id_idx on reminders (user_card_id);
create index if not exists reminders_remind_at_idx on reminders (remind_at);
create index if not exists reminders_status_idx on reminders (status);

-- ============================================================
-- USER_BENEFIT_PREFS — per-user benefit customization (paid)
-- ============================================================
create table if not exists user_benefit_prefs (
  id                uuid primary key default uuid_generate_v4(),
  user_id           uuid not null references auth.users (id) on delete cascade,
  benefit_id        uuid not null references benefits (id) on delete cascade,
  enabled           boolean not null default true,
  custom_lead_days  int,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create unique index if not exists user_benefit_prefs_idx on user_benefit_prefs (user_id, benefit_id);

-- ============================================================
-- SUBSCRIPTIONS — Stripe billing state
-- ============================================================
create table if not exists subscriptions (
  id                      uuid primary key default uuid_generate_v4(),
  user_id                 uuid not null unique references auth.users (id) on delete cascade,
  stripe_customer_id      text unique,
  stripe_subscription_id  text unique,
  plan                    text not null default 'free', -- free | pro
  status                  text not null default 'active', -- active | past_due | canceled | trialing
  trial_end               timestamptz,
  current_period_start    timestamptz,
  current_period_end      timestamptz,
  cancel_at_period_end    boolean not null default false,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table cards enable row level security;
alter table benefits enable row level security;
alter table user_cards enable row level security;
alter table reminders enable row level security;
alter table user_benefit_prefs enable row level security;
alter table subscriptions enable row level security;

-- Cards: publicly readable
create policy "cards_public_read" on cards for select using (true);
create policy "cards_service_write" on cards for all using (auth.role() = 'service_role');

-- Benefits: publicly readable
create policy "benefits_public_read" on benefits for select using (true);
create policy "benefits_service_write" on benefits for all using (auth.role() = 'service_role');

-- User cards: owner only
create policy "user_cards_owner" on user_cards for all using (auth.uid() = user_id);

-- Reminders: owner only
create policy "reminders_owner" on reminders for all using (auth.uid() = user_id);

-- User benefit prefs: owner only
create policy "user_benefit_prefs_owner" on user_benefit_prefs for all using (auth.uid() = user_id);

-- Subscriptions: owner read; service role write
create policy "subscriptions_owner_read" on subscriptions for select using (auth.uid() = user_id);
create policy "subscriptions_service_write" on subscriptions for all using (auth.role() = 'service_role');

-- ============================================================
-- UPDATED_AT trigger helper
-- ============================================================
create or replace function update_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger cards_updated_at before update on cards
  for each row execute function update_updated_at();
create trigger benefits_updated_at before update on benefits
  for each row execute function update_updated_at();
create trigger subscriptions_updated_at before update on subscriptions
  for each row execute function update_updated_at();
create trigger user_benefit_prefs_updated_at before update on user_benefit_prefs
  for each row execute function update_updated_at();
